# Generated by Django 5.1.1 on 2026-09-26 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedopportunity',
            options={'ordering': ['-saved_at']},
        ),
    ]
