# Generated by Django 5.1.1 on 2026-09-25 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchsource',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fetch_sources', to='opportunities.opportunitycategory'),
        ),
        migrations.AddField(
            model_name='fetchlog',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ingestion.fetchsource'),
        ),
        migrations.AddIndex(
            model_name='fetchsource',
            index=models.Index(fields=['is_active'], name='ingestion_f_is_acti_02b1a3_idx'),
        ),
        migrations.AddIndex(
            model_name='fetchlog',
            index=models.Index(fields=['source', '-started_at'], name='ingestion_f_source__1974bd_idx'),
        ),
    ]
